name: gitme_reborn
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  flutter_progress_hud: ^1.0.2
  flutter_launcher_icons: ^0.7.3
  flutter_dotenv: ^2.0.3
  package_info: ^0.4.0+6
  url_launcher: ^5.1.2
  timeago: ^2.0.19

  # API Usage
  hnpwa_client: ^2.0.0
  github: ^5.1.0

  # JSON Parsing
  json_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # JSON Parsing
  build_runner: ^1.0.0
  json_serializable: ^3.2.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - .env

  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icons/gitme-reborn-logo.png"
